name: submission
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  camera: ^0.12.0+1
  flutter:
    sdk: flutter

  google_generative_ai: ^0.4.7
  http: ^1.6.0
  image: ^4.8.0
  image_cropper: ^12.2.1
  image_picker: ^1.2.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.3
  provider: ^6.1.2
  shimmer: ^3.0.0
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ml/food_classifier.tflite
    - assets/ml/labels.txt
